# Generated by Django 3.1 on 2022-04-11 19:09

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_page', '0001_initial'),
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Имя')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, default='', max_length=150, unique=True, verbose_name='ЧПУ')),
            ],
            options={
                'verbose_name': 'Тип жилья',
                'verbose_name_plural': 'Типы жилья',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, default='', max_length=150, unique=True, verbose_name='ЧПУ')),
            ],
            options={
                'verbose_name': 'Инфраструктура',
                'verbose_name_plural': 'Инфраструктуры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HotelsPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
                ('heading', models.TextField(verbose_name='Заголовок')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('html_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_HotelsPage', to='show.template', verbose_name='html_template')),
            ],
            options={
                'verbose_name': 'HotelsPage',
                'verbose_name_plural': 'HotelsPages',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Картинка')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='rating')),
                ('min_price', models.FloatField(blank=True, null=True, verbose_name='Цена от')),
                ('max_price', models.FloatField(blank=True, null=True, verbose_name='Цена до')),
                ('star', models.SmallIntegerField(blank=True, null=True, verbose_name='star')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='wifi')),
                ('has_pool', models.BooleanField(default=False, verbose_name='pool')),
                ('has_parking', models.BooleanField(default=False, verbose_name='parking')),
                ('housing_type_text_choices', models.CharField(blank=True, choices=[(None, 'Выберите тип жилья'), ('Hotel', 'Гостиница'), ('Motel', 'Мотель'), ('Apartment', 'Апартамент')], max_length=16, null=True, verbose_name='тип жилья')),
                ('slug', models.SlugField(blank=True, default='', max_length=150, unique=True, verbose_name='ЧПУ')),
                ('housing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_type_hotel2', to='hotels.housingtype', verbose_name='тип жилья')),
                ('infrastructure', models.ManyToManyField(blank=True, related_name='housing_type_infrastructure', to='hotels.Infrastructure', verbose_name='инфраструктура')),
            ],
            options={
                'verbose_name': 'Гостиница',
                'verbose_name_plural': 'Гостиницы',
                'ordering': ('name',),
            },
        ),
    ]
